name: rwa
services:
  ingester:
    env_file: .env
    build:
      context: ingester
    volumes:
      - type: bind
        source: ./logs
        target: /logs

  consumer:
    env_file: .env
    build:
      context: consumer
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./channels.conf
        target: /app/channels.conf

  bot:
    env_file: .env
    build:
      context: bot
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./logs
        target: /logs