[project]
name = "consumer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "launchdarkly-eventsource>=1.3.0",
    "supabase>=2.20.0",
]
