[project]
name = "consumer"
version = "0.1.0"
description = "Utility that consumes events from the NationStates SSE feed and updates a Supabase database accordingly."
requires-python = ">=3.13"
dependencies = [
    "launchdarkly-eventsource>=1.3.0",
    "supabase>=2.20.0",
]
