[project]
name = "ingester"
version = "0.1.0"
description = "Utility to ingest daily dumps from NationStates"
requires-python = ">=3.13"
dependencies = [
    "psycopg[binary]>=3.2.10",
    "sans>=1.3.2",
]
