[project]
name = "ingester"
version = "0.1.0"
description = "Utility to ingest daily dumps from NationStates"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "supabase>=2.20.0",
]
