[project]
name = "bot"
version = "0.1.0"
description = "Discord bot to interface with the database and provide real-time WA updates."
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "discord-py>=2.6.3",
    "psycopg[binary]>=3.2.10",
    "sans>=1.3.2",
]
